version: '3.9'
services: 
  app:
    container_name: test_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 5000:5000
      - 5001:5001
      - 44378:44378
    depends_on: 
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks: 
      - test
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: 
      - test

networks:
  test: